### ISSUE TITLE
10th Lineage OS 17.1 Testing PreBuilt Vendor Logs & Boot Details

### ISSUE THREAD

**Issue by ghost** [sm7150/android_device_samsung_a70q#1]
#### Currently stuck in lineage logo instead of Samsung logo

- Fixable since lineage logo showing & flashing
- Doesn't boot straight into download mode nor bootloader, only stuck in lineage logo (looking good)
- Plenty & Useful logs grabbed/spoofed

#### Logs of the bootloop (stuck in lineage logo)

[__Pastebin Whole Ramoops Logs__](https://pastebin.com/PjJQjsP3)
[__DogBin Whole Ramoops Logs__](https://del.dog/etamingigr.txt)
[__Ramoops Log Whole File__](https://github.com/sm7150/device_samsung_a70q/releases/download/17.1t10/console-ramoops-0_bdAaBN)

**Comment by ghost** [comment]
#### AVC SeLinux Denials

- DogBin Whole Log (__Line Number:__) ```317-329```

**Comment by githdavro** [comment]
Epic

**Comment by ghost** [comment]
Issues Resolved & Fixed!
